version: "3.9"
services:
  postgres:
    image: postgres:13
    volumes:
      - ./migration/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_DB: "weather_tracker"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"